### ISSUE TITLE
Stuck at Resolvers.get

### ISSUE THREAD

**Issue by eernstg** [dart-lang/code_transformers#29]
In some cases the `get` method on an instance of `Resolvers` from 'resolvers.dart' gets stuck, in the sense that the next statement after `await` never gets executed:

```dart
  Resolvers resolvers = ..;
  Resolver resolver = await resolvers.get(myTransform);
  // not reached
```
The problem is easy to reproduce:
```
  git clone 'https://github.com/dart-lang/reflectable'
  cd reflectable/tool
  git co 64be223a843f31b799b1170de4fe786e0468c32a
  ./bottest
```

This will end in a state where the `pub build --mode=debug test` process is stuck. The actual location where it is stuck is at line 2741 in 'lib/src/transformer_implementation.dart'. Note that the stuck state may hereafter be reproduced much faster by running `pub build --mode=debug test` directly in the 'test_reflectable' subdirectory (`cd ../test_reflectable` in the above setting).

We have noticed that the problem disappears when we use a dependency_override such that the version of the analyzer is 0.26.1+14 rather than 0.26.2. Because of this fact, we have reported the same issue on the analyzer repo: https://github.com/dart-lang/analyzer_cli/issues/73.

Update: Reflectable has a new commit doing the dependency override on the analyzer that prevents the above problem, so the `git clone` above must fetch commit 64be223a843f31b799b1170de4fe786e0468c32a rather than the most recent one. I edited the text above to reflect this fact.

**Comment by jakemac53** [comment]
see https://github.com/dart-lang/sdk/issues/24735 as well, may or may not be related

**Comment by jakemac53** [comment]
Closing this as I assume it is stale, please re-open if that is not the case
