### ISSUE TITLE
Renamed project to code_transformers

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/code_transformers#4]
For consistency

**Comment by sigmundch** [comment]
Note we can't do the rename without also submitting a fix to the build bot infrastructure (see http://build.chromium.org/p/client.dart.packages/), otherwise the bots will not follow the new changes in this repo.

**Comment by jakemac53** [comment]
oh whoops, I already did this. However, I think it should be ok because github has redirect set up for everything? I will check to see if its working currently.

**Comment by jakemac53** [comment]
looks like its fine!
