### ISSUE TITLE
Should fix for `1.22` dev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/code_transformers#56]
https://travis-ci.org/dart-lang/code_transformers/jobs/197457714#L229

Travis is failing. Let's get this running.

**Comment by kevmoo** [comment]
CC @natebosch @jakemac53

**Comment by natebosch** [comment]
This is an interesting regression in the language. We could hack around it but IMO it would be a little ugly. Will leave this failing for now while we discuss whether the language should allow this.

**Comment by kevmoo** [comment]
@natebosch to follow-up w/ language folks in SEA nowish?

**Comment by jakemac53** [comment]
I agree with @natebosch that this seems like a regression in the language that should be fixed.

**Comment by natebosch** [comment]
yeah I did, I'm working on the issue against the SDK now

**Comment by natebosch** [comment]
https://github.com/dart-lang/sdk/issues/28647

**Comment by natebosch** [comment]
The change got in to 1.22 I think this should be passing now.
