### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/code_transformers#63]
running tests in Dart 2 mode

00:02 +0 -1: can benchmark transformers [E]                                                                                                                                                            
  type 'Future<dynamic>' is not a subtype of type 'FutureOr<bool>' where
    Future is from dart:async
    FutureOr is from dart:async
    bool is from dart:core
  
  package:code_transformers/src/async_benchmark_base.dart 48:18                          AsyncBenchmarkBase.measureFor.<fn>
  dart:async                                                                             Future.doWhile
  package:code_transformers/src/async_benchmark_base.dart 46:19                          AsyncBenchmarkBase.measureFor
  package:code_transformers/src/async_benchmark_base.dart 61:11                          AsyncBenchmarkBase.measure
  ===== asynchronous gap ===========================
  dart:async                                                                             Future.doWhile
  package:code_transformers/src/async_benchmark_base.dart 46:19                          AsyncBenchmarkBase.measureFor
  package:code_transformers/src/async_benchmark_base.dart 61:11                          AsyncBenchmarkBase.measure
  ===== asynchronous gap ===========================
  dart:async                                                                             Future.doWhile
  package:code_transformers/src/async_benchmark_base.dart 46:19                          AsyncBenchmarkBase.measureFor
  package:code_transformers/src/async_benchmark_base.dart 61:11                          AsyncBenchmarkBase.measure
  ===== asynchronous gap ===========================
  dart:async                                                                             _asyncThenWrapperHelper
  package:code_transformers/src/async_benchmark_base.dart                                AsyncBenchmarkBase.measure
  ../..code_transformers/test/benchmarks_test.dart 22:22  main.<fn>

 type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, Iterable<dynamic>>' in type cast where
    _InternalLinkedHashMap is from dart:collection
    Map is from dart:core
    String is from dart:core
    Iterable is from dart:core
  
  dart:core                                                                             Object._as
  ../../code_transformers/test/messages_test.dart 101:54  main.<fn>.<fn>

**Comment by natebosch** [comment]
cc @jakemac53 

We're planning on deprecating this package. I wonder if we can do that quick enough that we don't need to fix these?

**Comment by jakemac53** [comment]
Yes, IMO we just drop this package entirely for Dart 2. It has no use anyways since transformers are not a thing and we have forked the resolver implementation already.
